services:
  db:
    image: mysql:latest
    container_name: mysql-server
    environment:
      MYSQL_ROOT_USER: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: "America/New_York"
      tty: true
    ports:
        - 3306:3306
    volumes:
        - $HOME/mysql:/var/lib/mysql