services:
  db:
    image: mysql:latest
    container_name: mysql-server
    environment:
      MYSQL_ROOT_USER: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: "America/Toronto"
      tty: true
    ports:
        - 3306:3306
    volumes:
        - $HOME/mysql:/var/lib/mysql
    tty: true
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ABSOLUTE_URI: "http://localhost:8080"
    ports:
      - "8080:80"
    depends_on:
      - db